package com.spring.implementation.dto.enums;

public enum ResponseCode {

    INTERNAL_ERROR,
    ACCESS_DENIED,
    USER_NOT_FOUND,
    USER_ALREADY_EXIST,
    BAD_REQUEST,
    NOT_FOUND,
    CREATED,
    SERVICE_UNAVAILABLE,
    UNAUTHORIZED,
    INVALID_INPUT,
    INVALID_RESPONSE,
    LOGOUT_RESPONSE,

    DB_ERROR,
    IAM_ERROR,
    AWS_ERROR,

    ENTITY,
    OK,
    UPDATED,
    UNSUPPORTED_MEDIA_TYPE,
    CHECK_CONSULT_TIME,
    INVALID_TIME_DURATION,
    PAST_START_TIME,
    SLOT_ALREADY_BOOKED,
    SLOT_NOT_FOUND,
    NO_NOTIFICATIONS,
    NOTIFICATION_MARKED_AS_SEEN,

    AWS_EVENT_BRIDGE_SCHEDULER_CONFLICT,
    TOO_MANY_REQUESTS,
    CONFLICT;
}
